### ISSUE TITLE
Two things to change .

### ISSUE THREAD

**Issue by SulimanTwfiq** [Zyst/Egoist-One#1]
Hey , 
Here 'in' color should be like 'let' color  
![forin](https://user-images.githubusercontent.com/32466357/41266468-a423cb88-6dff-11e8-877d-9c4e5725f7d8.JPG)

Can you please make the properties colors different than the variable name ? 
![ingredients_prices](https://user-images.githubusercontent.com/32466357/41266470-a454fd7a-6dff-11e8-99b3-56dc79d2b3ba.JPG)

Thank you .

**Comment by Zyst** [comment]
For the second one:

![image](https://user-images.githubusercontent.com/3832380/41308135-b5721548-6e40-11e8-9f5e-36fd9f5d17ea.png)

Constants are yellow, not variables. Anyway, I like constants being yellow. That one is not getting changed.

For the first one `forin` loops already have a notation color, but it's dependent on https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

![image](https://user-images.githubusercontent.com/3832380/41308227-f502a81c-6e40-11e8-8dea-6b27b02c9872.png)

Looking at the TM Scope, `in` doesn't get a variable of its own. So I can't change it to be orange without breaking something else.

![image](https://user-images.githubusercontent.com/3832380/41308256-0f7e5ca4-6e41-11e8-96cd-439462ce4491.png)

It might be worthwhile to some day skin all of this out with the Vanilla VS Code JavaScript at some point, but I don't particularly have plans to do so right now.

EDIT: Above said, if you feel like doing it yourself, and making a pull request that'd be more than welcome. For now I'm fine with using the Babel notation plugin, however.
