### ISSUE TITLE
Fix the new colors

### ISSUE THREAD

**Issue by lomeat** [Zyst/Egoist-One#2]
Hello, I cant understand where is the problem with my theme. I updated VS Code to the newest version and got your theme-look like One Dark. All phrase "this.variable.property" is red, instead of only "this" red and other words after dot are grey. For that I like your theme. Harder to understand code when all is red (like in vanilla one dark pro).
But now difference only in orange colors.

Love your fork, please fix or explain that.

Old variant (default, I want to return back it)
![egois_2](https://user-images.githubusercontent.com/33469504/76765193-118eec00-67a7-11ea-849e-31cc9d61c8e9.PNG)

New all red:
![egois_1](https://user-images.githubusercontent.com/33469504/76765214-1653a000-67a7-11ea-8c0c-5ea68d3e836d.PNG)

**Comment by Zyst** [comment]
I think I had this plugin installed:

https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

Do you have that plugin installed as well? That might be it.

Either way, I don't use VS Code anymore, and don't really plan on fixing this. If you make a PR I'll be happy to merge it though.

**Comment by lomeat** [comment]
Plugin do not belong to this

Noticed when you just opened editor, color scheme looks like usually, but when all 'JS/TS features' finishing loading in system editor tray then color gone red. 

I'll write it off later when I solve the problem

**Comment by lomeat** [comment]
So,
I tried to find a bug, but everything tell that all good. Reinstalling editor not helps. But, I download VS Code Insiders (which installs separate withCode) and there is no problem with wrong highlight. 
Maybe problem with my config of settings. But I dont know where.

Your theme does not have issues.
